import { Injectable } from '@angular/core';
import { FightEquipmentService } from './fight-equipment.service';

@Injectable({ providedIn: 'root' })
export class EquipmentService {
  tools :Tool[] =[
    { title: 'abaco', weight: 1, price: 0 },
    { title: 'abito comune', weight:1.5 , price: 0 },
    { title: 'abito costume', weight:2 , price: 0 },
    { title: 'abito da viaggiatore', weight:2 , price: 0 },
    { title: 'abito pregiato', weight:3 , price: 0 },
    { title: 'acciarino e pietra focaia', weight:0.5 , price: 0 },
    { title: 'acqua santa (ampolla)', weight:0.5 , price: 0 },
    { title: 'aghi da cerbottana', weight:0.01 , price: 0 },
    { title: "acciarino e pietra focaia", weight: 0.5 , price: 0 },
    { title: "acqua santa (ampolla)", weight: 0.5 , price: 0 },
    { title: "aghi da cerbottana", weight: 0.01 , price: 0 },
    { title: "ampolla o boccale", weight: 0.5 , price: 0 },
    { title: "amuleto", weight: 0.5 , price: 0 },
    { title: "anello con sigillo", weight: 0 , price: 0 },
    { title: "ariete portatile", weight: 17.5 , price: 0 },
    { title: "asta (3m)", weight: 3.5 , price: 0 },
    { title: "attrezzi da scalatore", weight: 6 , price: 0 },
    { title: "barile", weight: 35 , price: 0 },
    { title: "bacchetta", weight: 0.5 , price: 0 },
    { title: "bastone", weight: 2 , price: 0 },
    { title: "bilancia da mercante", weight: 1.5 , price: 0 },
    { title: "borsa", weight: 0.5 , price: 0 },
    { title: "borsa del guaritore", weight: 1.5 , price: 0 },
    { title: "borsa per componenti", weight: 1 , price: 0 },
    { title: "bottiglia di vetro", weight: 1 , price: 0 },
    { title: "boccetta d'inchiostro", weight: 0.3 , price: 0 },
    { title: "brocca o carraffa", weight: 2 , price: 0 },
    { title: "bacchetta in legno di tasso", weight: 0.5 , price: 0 },
    { title: "bastone di legno", weight: 2 , price: 0 },
    { title: "campanella", weight: 0 , price: 0 },
    { title: "candela", weight: 0 , price: 0 },
    { title: "canestro", weight: 1 , price: 0 },
    { title: "canna da pesca", weight: 2 , price: 0 },
    { title: "cannochiale", weight: 0.5 , price: 0 },
    { title: "carrucola e paranco", weight: 2.5 , price: 0 },
    { title: "catena (3m)", weight: 5 , price: 0 },
    { title: "cera per sigillo", weight: 0 , price: 0 },
    { title: "chiodo da rocciatore", weight: 0.125 , price: 0 },
    { title: "clessidra", weight: 0.5 , price: 0 },
    { title: "coperta", weight: 1.5 , price: 0 },
    { title: "corda di canapa (15m)", weight: 5 , price: 0 },
    { title: "corda di seta (15m)", weight: 2.5 , price: 0 },
    { title: "cote per affilare", weight: 0.5 , price: 0 },
    { title: "custodia pergamene", weight: 0.5 , price: 0 },
    { title: "custodia quadrelli", weight: 0.5 , price: 0 },
    { title: "cristallo", weight: 0.5 , price: 0 },
    { title: "emblema", weight: 0 , price: 0 },
    { title: "faretra", weight: 0.5 , price: 0 },
    { title: "fiala", weight: 0 , price: 0 },
    { title: "fischietto da richiamo", weight: 0 , price: 0 },
    { title: "foglio carta", weight: 0 , price: 0 },
    { title: "forziere", weight: 12.5 , price: 0 },
    { title: "fuoco dell'alchimista (ampolla)", weight: 0.5 , price: 0 },
    { title: "fiala di acido", weight: 0.5 , price: 0 },
    { title: "fiala di veleno", weight: 0 , price: 0 },
    { title: "fiala antitossina", weight: 0 , price: 0 },
    { title: "freccie", weight: 0.025 , price: 0 },
    { title: "foglio pergamena", weight: 0 , price: 0 },
    { title: "fiala di profumo", weight: 0 , price: 0 },
    { title: "globo", weight: 1.5 , price: 0 },
    { title: "gavetta (kit da pranzo)", weight: 0.5 , price: 0 },
    { title: "gessetto", weight: 0 , price: 0 },
    { title: "giaciglio (sacco a pelo)", weight: 3.5 , price: 0 },
    { title: "lampada", weight: 0.5 , price: 0 },
    { title: "lanterna a lente sporgente", weight: 1 , price: 0 },
    { title: "lanterna schermabile", weight: 1 , price: 0 },
    { title: "lente d'ingrandimento", weight: 0 , price: 0 },
    { title: "libro", weight: 2.5 , price: 0 },
    { title: "libro degli incantesimi", weight: 1.5 , price: 0 },
    { title: "manette", weight: 3 , price: 0 },
    { title: "martello", weight: 1.5 , price: 0 },
    { title: "martello da demolizione", weight: 5 , price: 0 },
    { title: "otre (borraccia)", weight: 2.5 , price: 0 },
    { title: "pennino", weight: 0 , price: 0 },
    { title: "piccone da minatore", weight: 5 , price: 0 },
    { title: "piede di porco", weight: 2.5 , price: 0 },
    { title: "pozione di guarigione", weight: 0.25 , price: 0 },
    { title: "proiettili da fionda", weight: 0.0375 , price: 0 },
    { title: "quadrelli da balestra", weight: 0.0375 , price: 0 },
    { title: "rampino", weight: 2 , price: 0 },
    { title: "razione giornaliera", weight: 1 , price: 0 },
    { title: "rametto di vischio", weight: 0 , price: 0 },
    { title: "reliquiario", weight: 1 , price: 0 },
    { title: "sacco", weight: 0.25 , price: 0 },
    { title: "sapone", weight: 0 , price: 0 },
    { title: "scala a pioli (3m)", weight: 12.5 , price: 0 },
    { title: "secchio", weight: 1 , price: 0 },
    { title: "serratura", weight: 0.5 , price: 0 },
    { title: "sfere metalliche (1000)", weight: 1 , price: 0 },
    { title: "specchio piccolo di metallo", weight: 0.25 , price: 0 },
    { title: "spuntoni di ferro", weight: 0.25 , price: 0 },
    { title: "tagliola", weight: 12.5 , price: 0 },
    { title: "tenda per 2", weight: 10 , price: 0 },
    { title: "torcia", weight: 0.5 , price: 0 },
    { title: "totem", weight: 0 , price: 0 },
    { title: "triboli", weight: 0.1 , price: 0 },
    { title: "vanga o badile", weight: 2.5 , price: 0 },
    { title: "vaso di ferro", weight: 5 , price: 0 },
    { title: "veste", weight: 2 , price: 0 },
    { title: "verga", weight: 1 , price: 0 },
    { title: "zaino", weight: 2.5 , price: 0 },
    // { title:'',weight:0 , price: 0 },
  ]
  toolWeight(toolTitle:string, toolAmount:number){
    const toolWeight =this.tools 
      .filter(tool=>toolTitle.toLowerCase().includes(tool.title))
    return toolWeight.length>0 ?toolWeight[0].weight *toolAmount :0
  }

  constructor(private fes:FightEquipmentService){
    const union =[...fes.armors, ...fes.weapones]
    union .map(tool=>{ 
      this.tools.push({ title: tool.title, weight: tool.weight, price: 0 }) 
    })
    // console.log( this.tools, );
  }
}
export interface Tool{
  title:string, 
  weight:number, 
  amount?:number, 
  price:number,
}