import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class EquipmentService {
  toolWeight(toolTitle:string, toolAmount:number){
    const toolWeight =this.tools 
      .filter(tool=>tool.title.includes(toolTitle.toLowerCase()))
    return toolWeight.length>0 ?toolWeight[0].weight *toolAmount :0
  }
  tools =[
    { title: 'abaco', weight:1 },
    { title: 'abito comune', weight:1.5 },
    { title: 'abito costume', weight:2 },
    { title: 'abito da viaggiatore', weight:2 },
    { title: 'abito pregiato', weight:3 },
    { title: 'acciarino e pietra focaia', weight:0.5 },
    { title: 'acqua santa (ampolla)', weight:0.5 },
    { title: 'aghi da cerbottana', weight:0.01 },
    { title: "acciarino e pietra focaia", weight: 0.5 },
    { title: "acqua santa (ampolla)", weight: 0.5 },
    { title: "aghi da cerbottana", weight: 0.01 },
    { title: "ampolla o boccale", weight: 0.5 },
    { title: "amuleto", weight: 0.5 },
    { title: "anello con sigillo", weight: 0 },
    { title: "ariete portatile", weight: 17.5 },
    { title: "asta (3m)", weight: 3.5 },
    { title: "attrezzi da scalatore", weight: 6 },
    { title: "barile", weight: 35 },
    { title: "bacchetta", weight: 0.5 },
    { title: "bastone", weight: 2 },
    { title: "bilancia da mercante", weight: 1.5 },
    { title: "borsa", weight: 0.5 },
    { title: "borsa del guaritore", weight: 1.5 },
    { title: "borsa per componenti", weight: 1 },
    { title: "bottiglia di vetro", weight: 1 },
    { title: "boccetta d'inchiostro", weight: 0.3 },
    { title: "brocca o carraffa", weight: 2 },
    { title: "bacchetta in legno di tasso", weight: 0.5 },
    { title: "bastone di legno", weight: 2 },
    { title: "campanella", weight: 0 },
    { title: "candela", weight: 0 },
    { title: "canestro", weight: 1 },
    { title: "canna da pesca", weight: 2 },
    { title: "cannochiale", weight: 0.5 },
    { title: "carrucola e paranco", weight: 2.5 },
    { title: "catena (3m)", weight: 5 },
    { title: "cera per sigillo", weight: 0 },
    { title: "chiodo da rocciatore", weight: 0.125 },
    { title: "clessidra", weight: 0.5 },
    { title: "coperta", weight: 1.5 },
    { title: "corda di canapa (15m)", weight: 5 },
    { title: "corda di seta (15m)", weight: 2.5 },
    { title: "cote per affilare", weight: 0.5 },
    { title: "custodia pergamene", weight: 0.5 },
    { title: "custodia quadrelli", weight: 0.5 },
    { title: "cristallo", weight: 0.5 },
    { title: "emblema", weight: 0 },
    { title: "faretra", weight: 0.5 },
    { title: "fiala", weight: 0 },
    { title: "fischietto da richiamo", weight: 0 },
    { title: "foglio carta", weight: 0 },
    { title: "forziere", weight: 12.5 },
    { title: "fuoco dell'alchimista (ampolla)", weight: 0.5 },
    { title: "fiala di acido", weight: 0.5 },
    { title: "fiala di veleno", weight: 0 },
    { title: "fiala antitossina", weight: 0 },
    { title: "freccie", weight: 0.025 },
    { title: "foglio pergamena", weight: 0 },
    { title: "fiala di profumo", weight: 0 },
    { title: "globo", weight: 1.5 },
    { title: "gavetta (kit da pranzo)", weight: 0.5 },
    { title: "gessetto", weight: 0 },
    { title: "giaciglio (sacco a pelo)", weight: 3.5 },
    { title: "lampada", weight: 0.5 },
    { title: "lanterna a lente sporgente", weight: 1 },
    { title: "lanterna schermabile", weight: 1 },
    { title: "lente d'ingrandimento", weight: 0 },
    { title: "libro", weight: 2.5 },
    { title: "libro degli incantesimi", weight: 1.5 },
    { title: "manette", weight: 3 },
    { title: "martello", weight: 1.5 },
    { title: "martello da demolizione", weight: 5 },
    { title: "otre (borraccia)", weight: 2.5 },
    { title: "pennino", weight: 0 },
    { title: "piccone da minatore", weight: 5 },
    { title: "piede di porco", weight: 2.5 },
    { title: "pozione di guarigione", weight: 0.25 },
    { title: "proiettili da fionda", weight: 0.0375 },
    { title: "quadrelli da balestra", weight: 0.0375 },
    { title: "rampino", weight: 2 },
    { title: "razione giornaliera", weight: 1 },
    { title: "rametto di vischio", weight: 0 },
    { title: "reliquiario", weight: 1 },
    { title: "sacco", weight: 0.25 },
    { title: "sapone", weight: 0 },
    { title: "scala a pioli (3m)", weight: 12.5 },
    { title: "secchio", weight: 1 },
    { title: "serratura", weight: 0.5 },
    { title: "sfere metalliche (1000)", weight: 1 },
    { title: "specchio piccolo di metallo", weight: 0.25 },
    { title: "spuntoni di ferro", weight: 0.25 },
    { title: "tagliola", weight: 12.5 },
    { title: "tenda per 2", weight: 10 },
    { title: "torcia", weight: 0.5 },
    { title: "totem", weight: 0 },
    { title: "triboli", weight: 0.1 },
    { title: "vanga o badile", weight: 2.5 },
    { title: "vaso di ferro", weight: 5 },
    { title: "veste", weight: 2 },
    { title: "verga", weight: 1 },
    { title: "zaino", weight: 2.5 },
    
    // EQUIPAGGIAMENTO BELLICO
    { title: "armatura di cuoio", weight: 5 },
    { title: "cotta di maglia", weight: 20.7 },
    { title: "armatura a piastre", weight: 32.5 },

    { title: "scudo a brochiero", weight: 1 }, 
    { title: "pugnale da parata", weight: 1 }, 
    { title: "cappa da parata", weight: 3 }, 
    { title: "scudo a rotella", weight: 6 }, 
    { title: "scudo a torre", weight: 10 }, 

    { title: "arma inastata", weight: 1.5 }, 
    { title: "arma inastata pesante", weight: 3 }, 
    { title: "arma pesante", weight: 3 }, 
    { title: "arma bilanbiata lunga", weight: 1 }, 
    { title: "arma bilanciata corta", weight: 1 },
    { title: "arma sbilanciata scure", weight: 2 }, 
    { title: "arma sbilanciata mazza", weight: 5 }, 
    { title: "flagello", weight: 5 }, 
    { title: "arma piccola", weight: 0.5 }, 
    { title: "tirapugni borchiato", weight: 0.5 }, 

    { title: "fucile", weight: 4 },
    { title: "arco", weight: 2 },
    { title: "pistola", weight: 1.5 }, 


    // { title:'',weight:0 },
  ]
}
